version: "3.5"

services: 
  manager-task:
   container_name: manager-task
   build: 
    context: .
    dockerfile: Dockerfile.dev
   restart: always
   ports:
    - 4001:4001
   volumes:
    - .:/app/manager-task
    - /app/manager-task/node_modules
    - /app/rota36/.next
 
